//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace greenfrog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveStream
    {
        public int idLiveStream { get; set; }
        public string noidunglive { get; set; }
        public string hinh { get; set; }
        public string link { get; set; }
    }
}
